finance/urls.py
from django.conf.urls import url

from .views import start, success, cancel, index

urlpatterns = [
    url(r'^success/$', success),
    url('^start/$', start, name='payment_start'),
    url('^cancel/$', cancel),
    url('^index/$', index, name='payment_index')
]

opencabs/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^' + settings.URL_PREFIX + r'$', views.booking_wizard, name='index'),
    url(r'^' + settings.URL_PREFIX + r'booking/$', views.booking_details,
        name='booking_details'),
    url(r'^' + settings.URL_PREFIX + 'booking/(?P<booking_id>\d+)/invoice/$',
        views.booking_invoice, name='booking_invoice'),
    url(r'^' + settings.URL_PREFIX + r'payment/', include('finance.urls')),
    url(r'^' + settings.URL_PREFIX + r'admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    url(r'^' + settings.URL_PREFIX + r'(?P<url>.*/)$', flatpages_views.flatpage),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

opencabs/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.contrib.contenttypes.fields import GenericRelation
from django.utils import timezone
from django.core.mail import send_mail

from finance.models import Payment

import json
import os
import uuid
from io import StringIO
from hashlib import md5
from datetime import datetime
from collections import OrderedDict

from utils.pdf import draw_pdf

from .notification import send_sms


class VehicleFeature(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField(max_length=100, blank=True, default='')

    created = models.DateTimeField(auto_now_add=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True, blank=True)

    def __str__(self):
        return self.name


class VehicleCategory(models.Model):
    name = models.CharField(max_length=100, unique=True, db_index=True)
    description = models.TextField(max_length=200, blank=True, default='')
    image = models.ImageField(
        upload_to='vehicles',
        max_length=100, null=True, blank=True)

    passengers = models.IntegerField(default=4, blank=True)

    def __str__(self):
        return self.name


class VehicleRateCategory(models.Model):
    name = models.CharField(max_length=30, db_index=True, unique=True)
    description = models.TextField(max_length=200, blank=True, default='')
    category = models.ForeignKey(VehicleCategory, db_index=True,
                                 on_delete=models.PROTECT)
    features = models.ManyToManyField(VehicleFeature, blank=True)
    tariff_per_min = models.PositiveIntegerField()
    tariff_after_kms = models.PositiveIntegerField()

    created = models.DateTimeField(auto_now_add=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True, blank=True)

    class Meta:
        unique_together = ('name', 'category')

    def __str__(self):
        return self.name


class Place(models.Model):
    name = models.CharField(max_length=100, db_index=True, unique=True)

    created = models.DateTimeField(auto_now_add=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True, blank=True)

    def __str__(self):
        return self.name


class Rate(models.Model):
    source = models.ForeignKey(Place, on_delete=models.PROTECT,
                               related_name='rate_source')
    destination = models.ForeignKey(Place, on_delete=models.PROTECT,
                                    related_name='rate_destination')
    vehicle_category = models.ForeignKey(VehicleRateCategory,
                                         on_delete=models.PROTECT,
                                         related_name='rate', db_index=True)
    oneway_time = models.PositiveIntegerField()
    oneway_distance = models.PositiveIntegerField(default=0, blank=True)

    roundtrip_time = models.PositiveIntegerField(blank=True, default=0)
    roundtrip_distance = models.PositiveIntegerField(blank=True, default=0)

    code = models.CharField(max_length=100, editable=False, blank=True,
                            db_index=True)

    created = models.DateTimeField(auto_now_add=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True, blank=True)

    class Meta:
        unique_together = ('code', 'vehicle_category')

    def __str__(self):
        return '{}-{}'.format(self.source, self.destination)

    def save(self, *args, **kwargs):
        self.code = settings.ROUTE_CODE_FUNC(
            self.source.name, self.destination.name)
        if not self.roundtrip_time:
            self.roundtrip_time = 2 * self.oneway_time
        if not self.roundtrip_distance:
            self.roundtrip_distance = 2 * self.oneway_distance
        super().save(*args, **kwargs)

    @property
    def total_oneway_price(self):
        return int(round(self.oneway_time * (int)(self.vehicle_category.tariff_per_min)))

    @property
    def total_roundtrip_price(self):
        return int(round(self.roundtrip_time * (int)(self.vehicle_category.tariff_per_min) ))

    @property
    def tax_rate(self):
        if getattr(self, '_tax_rate', None):
            return self._tax_rate
        self._tax_rate = sum(
            [v['rate'] for v in settings.TAXES.values()])
        return self._tax_rate



class Driver(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    mobile = models.CharField(max_length=20, unique=True, db_index=True)

    def __str__(self):
        return '{}/{}'.format(self.name, self.mobile)


class Vehicle(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    number = models.CharField(max_length=20, unique=True, db_index=True)
    category = models.ForeignKey(
        VehicleCategory,
        on_delete=models.PROTECT)
    driver = models.OneToOneField(
        Driver,
        on_delete=models.PROTECT,
        unique=True,
        null=True,
        blank=True
    )

    def __str__(self):
        return '{}/{}'.format(self.name, self.number)


BOOKING_TYPE_CHOICES_DICT = getattr(
    settings, 'BOOKING_TYPE_CHOICES_DICT', OrderedDict(
        (
            ('OW', 'One way'),
            ('RT', 'Round trip')
        )
    )
)

BOOKING_STATUS_CHOICES_DICT = getattr(
    settings, 'BOOKING_STATUS_CHOICES_DICT', OrderedDict(
        (
            ('0', 'Request'),
            ('1', 'Confirmed'),
            ('2', 'Declined'),
            ('3', 'Attempt'),
        )
    )
)

BOOKING_PAYMENT_STATUS_CHOICES_DICT = getattr(
    settings, 'BOOKING_PAYMENT_STATUS_CHOICES_DICT', OrderedDict(
        (
            ('NP', 'Not paid'),
            ('PR', 'Partial'),
            ('PD', 'Paid'),
        )
    )
)

BOOKING_PAYMENT_METHOD_CHOICES_DICT = getattr(
    settings, 'BOOKING_PAYMENT_METHOD_CHOICES_DICT', OrderedDict(
        (
            ('POA', 'Pay on arrival'),
            ('ONL', 'Online'),
            ('', ''),
        )
    )
)


class Booking(models.Model):
    source = models.ForeignKey(Place, on_delete=models.PROTECT,
                               related_name='booking_source')
    destination = models.ForeignKey(Place, on_delete=models.PROTECT,
                                    related_name='booking_destination')
    pickup_point = models.TextField(max_length=200, blank=True, default="")
    booking_type = models.CharField(choices=BOOKING_TYPE_CHOICES_DICT.items(),
                                    max_length=2)
    travel_date = models.DateField()
    travel_time = models.TimeField()
    vehicle_type = models.ForeignKey(VehicleRateCategory,
                                     on_delete=models.PROTECT,
                                     related_name='booking')
    vehicle_count = models.PositiveIntegerField(default=1, blank=True)
    passengers = models.IntegerField(default=1, blank=True)
    customer_name = models.CharField(max_length=100, db_index=True,
                                     verbose_name='Name')
    customer_mobile = models.CharField(max_length=20, default='', blank=True,
                                       db_index=True, verbose_name='Mobile')
    customer_email = models.EmailField(default='', blank=True, db_index=True,
                                       verbose_name='Email')
    ssr = models.TextField(verbose_name='Special service request',
                           max_length=200, blank=True, default="",
                           help_text="Special service request")

    status = models.CharField(choices=BOOKING_STATUS_CHOICES_DICT.items(),
                              max_length=1,
                              default='0')
    payment_method = models.CharField(
        choices=BOOKING_PAYMENT_METHOD_CHOICES_DICT.items(), max_length=3,
        blank=True, null=True, default=''
    )
    payment_status = models.CharField(
        choices=BOOKING_PAYMENT_STATUS_CHOICES_DICT.items(), max_length=3,
        blank=True, null=True, default='NP')
    payment_done = models.PositiveIntegerField(blank=True, default=0)
    payment_due = models.PositiveIntegerField(blank=True, default=0)
    revenue = models.IntegerField(blank=True, default=0)
    last_payment_date = models.DateTimeField(blank=True, null=True)
    accounts_verified = models.BooleanField(default=False, db_index=True)
    payments = GenericRelation(Payment,
                               content_type_field='item_content_type',
                               object_id_field='item_object_id',
                               related_query_name='bookings')

    booking_id = models.CharField(max_length=20, blank=True, editable=False,
                                  db_index=True, unique=True)

    total_fare = models.PositiveIntegerField(blank=True, default=0)
    fare_details = models.TextField(blank=True, default="{}")
    distance = models.PositiveIntegerField(blank=True, null=True)

    created = models.DateTimeField(auto_now_add=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True, blank=True)

    drivers = models.CharField(max_length=500, default="", blank=True)

    def __str__(self):
        return self.booking_id

    @property
    def booking_type_display(self):
        return BOOKING_TYPE_CHOICES_DICT.get(self.booking_type)

    @property
    def humanized_payment_method(self):
        return BOOKING_PAYMENT_METHOD_CHOICES_DICT.get(self.payment_method)

    @property
    def humanized_payment_status(self):
        return BOOKING_PAYMENT_STATUS_CHOICES_DICT.get(self.payment_status)

    def get_admin_url(self):
        return reverse("admin:%s_%s_change" % (self._meta.app_label, self._meta.model_name), args=(self.id,))

    def save(self, *args, **kwargs):
        if not self.customer_email and not self.customer_mobile:
            raise ValidationError('Either of customer email and mobile is '
                                  'mandatory.')
        if self.id is None:
            self.booking_id = self._create_booking_id()

opencabs/views.py
import os

from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.urls import reverse
from django.core.mail import send_mail
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponse

from formtools.wizard.views import CookieWizardView

from .forms import booking as booking_form
from .models import Booking

FORMS = [
    ('itinerary', booking_form.BookingTravelForm),
    ('vehicles', booking_form.BookingVehiclesForm),
    ('contactinfo', booking_form.BookingContactInfoForm),
    ('paymentinfo', booking_form.BookingPaymentInfoForm),
]

TEMPLATES = {
    'itinerary': 'opencabs/index.html',
    'vehicles': 'opencabs/booking_vehicles.html',
    'contactinfo': 'opencabs/booking_contactinfo.html',
    'paymentinfo': 'opencabs/booking_paymentinfo.html',
}


class BookingWizard(CookieWizardView):

    form_list = FORMS

    def get_context_data(self, form, **kwargs):
        context_data = super().get_context_data(form, **kwargs)
        context_data['settings'] = settings
        return context_data

    def get_form_kwargs(self, step):
        data = {}
        if step == 'vehicles':
            itinerary_data = self.get_cleaned_data_for_step('itinerary')
            data.update({'source': itinerary_data['source'],
                         'destination': itinerary_data['destination'],
                         'booking_type': itinerary_data['booking_type']})
        return data

    def get_template_names(self):
        return [TEMPLATES[self.steps.current]]

    def done(self, form_list, form_dict, **kwargs):
        data = form_dict['itinerary'].cleaned_data
        data.update(form_dict['vehicles'].cleaned_data)
        contact_info = form_dict['contactinfo'].cleaned_data
        data.update(contact_info)
        payment_info = form_dict['paymentinfo'].cleaned_data
        data.update(payment_info)
        booking = Booking(**data)
        if booking.payment_method == 'ONL':
            booking.status = '3'
        booking.save()

        if booking.payment_method == 'ONL':
            payment = booking.payments.create(
                amount=booking.total_fare, type=1, mode='PG', status='WAT')
            return redirect(reverse('payment_start') + '?order_id=' + payment.invoice_id)
        else:
            booking.send_booking_request_ack_to_customer()
            return redirect(
                reverse('booking_details') + '?bookingid=' + booking.booking_id)

booking_wizard = BookingWizard.as_view()


def index(request):
    return render(request, 'opencabs/index.html', {
        'settings': settings,
        'wizard': booking_wizard
    })


def booking_details(request):
    booking_id = request.GET.get('bookingid', '').upper()
    booking = get_object_or_404(Booking, booking_id=booking_id)
    payment_status = ""
    order_id = request.GET.get('orderid', None)
    if order_id:
        payment = booking.payments.get(invoice_id=order_id)
        if payment.status in ['ERR', 'CAN', 'ABT', 'FAL']:
            payment_status = "failure"

    return render(request, 'opencabs/booking_details.html', {
        'settings': settings,
        'booking': booking,
        'payment_status': payment_status,
        'order_id': order_id
    })


@staff_member_required
def booking_invoice(request, booking_id):
    booking = Booking.objects.get(id=booking_id)
    path = booking.invoice()
    with open(path, 'rb') as f:
        response = HttpResponse(
            content=f.read(), content_type='application/pdf')
        os.remove(f.name)
        return response

opencabs/templates/opencabs/booking_contactinfo.html
{% extends "base.html" %}
{% load fieldsets %}

{% block content %}
    <h2>Enter your contact info!</h2>
    <form class="form-horizontal" action="" method="post" style="text-align: left;">{% csrf_token %}
        {{ wizard.management_form }}
        {% for error in wizard.form.non_field_errors %}
            <span class="help-block">{{ error }}</span>
        {% endfor %}
        {% get_fieldset customer_name,customer_mobile,customer_email as col1_fields from wizard.form %}
        {% get_fieldset pickup_point,ssr as col2_fields from wizard.form %}

        <div class="row">
            <div class="col-md-4">
                {% for field in col1_fields %}
                <div class="form-group {% if field.errors %}has-error{% endif %}">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {% for error in field.errors %}
                            <span class="help-block">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
            <div class="col-md-4 col-md-offset-1">
                {% for field in col2_fields %}
                <div class="form-group {% if field.errors %}has-error{% endif %}">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {% for error in field.errors %}
                            <span class="help-block">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
        </div>
        <input class="btn btn-primary" type="submit" value="Submit"></input>
    </form>
{% endblock %}

opencabs/templates/opencabs/booking_details.html
{% extends "base.html" %}

{% block content %}
<h2>Booking details</h2>
<div class="panel panel-info" style="text-align: left;">
    <div class="panel-body">
        <h2>Booking ID: {{ booking.booking_id }}</h2>

        <dl class="dl-horizontal">
            <dt>Status</dt>
            <dd>{{ booking.get_status_display }}</dd>

            <dt>Name</dt>
            <dd>{{ booking.customer_name }}</dd>

            <dt>Payment mode</dt>
            <dd>{{  booking.humanized_payment_method }}</dd>

            <dt>Payment status</dt>
            <dd>{{  booking.humanized_payment_status }}</dd>

            <dt>Source<dt>
            <dd>{{ booking.source }}</dd>

            <dt>Destination<dt>
            <dd>{{ booking.destination }}</dd>

            <dt>Booking type</dt>
            <dd>{{ booking.get_booking_type_display }}</dd>

            <dt>Travel datetime</dt>
            <dd>{{ booking.travel_date }} {{ booking.travel_time }}</dd>

            <dt>Vehicle type</dt>
            <dd>{{ booking.vehicle_type }}</dd>

            {% if booking.vehicle %}
            <dt>Vehicle</dt>
            <dd>{{ booking.vehicle }}</dd>
            {% endif %}

            {% if booking.driver %}
            <dt>Driver</dt>
            <dd>
                {{ booking.driver.name }}
                <i class="glyphicon glyphicon-earphone" style="padding-left:10px;"></i>
                <a href="tel:{{ booking.driver.mobile }}" style="color: white;">{{ booking.driver.mobile }}</a>
            </dd>
            {% endif %}

            {% if booking.extra_info %}
            <dt>Booking info</dt>
            <dd>{{ booking.extra_info }}</dd>
            {% endif %}
        </dl>
    </div>
</div>
<style>
    .dl-horizontal dt {
        text-align: left;
    }
</style>
{% endblock %}

opencabs/templates/opencabs/booking_paymentinfo.html
{% extends "base.html" %}
{% block content %}
<h2>Select payment method</h2>
<div class="panel panel-default">
    <div class="panel-body">
        <form action="" method="post">{% csrf_token %}
            {{ wizard.management_form }}
            <div class="row">
                <div class="col-md-4">
                    {{ form }}
                </div>
            </div>

            <br />
            <input class="btn btn-primary" type="submit" value="Make payment"></input>
        </form>
    </div>
</div>
{% endblock %}

opencabs/templates/opencabs/booking_vehicles.html
{% extends "base.html" %}

{% block content %}
<h2>Select your ride!</h2>
<div class="panel panel-default">
    <div class="panel-body">
        <form action="" method="post">{% csrf_token %}
            {{ wizard.management_form }}
            {% for radio in form.vehicle_type %}
            <div class="media vehicle">
                <div class="media-body">
                    {{ radio.choice_label }}
                </div>
                <div class="media-right">
                    <label for="{{ radio.label_for_id }}" class="select-vehicle btn btn-primary">
                        {{ radio.tag }} Select
                    </label>
                </div>
            </div>
            {% endfor %}

            <input type="submit" value="Submit" class="btn btn-primary btn-xl" style="display: none;"></input>
        </form>
   </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
$(function() {
    $('.select-vehicle').on('click', function (e) {
        $(e.target).find('input[type="radio"]').attr('checked', 'checked')
            .end()
            .parents('form').submit();
    });
}())
</script>
{% endblock %}

opencabs/templates/opencabs/index.html
{% extends "_base.html" %}

{% load i18n %}
{% load static %}

{% block extrahead %}
    <link href="{% static "css/bootstrap-datetimepicker.css" %}" rel="stylesheet">
	{{ wizard.form.media }}
    <style>
        .bootstrap-datetimepicker-widget.dropdown-menu {
            background-color: #483434;
        }
        .bootstrap-datetimepicker-widget table td.day:hover,
        .bootstrap-datetimepicker-widget table td.hour:hover,
        .bootstrap-datetimepicker-widget table td.minute:hover,
        .bootstrap-datetimepicker-widget table td.second:hover {
          background: #908b8b;
        }
        .bootstrap-datetimepicker-widget table td span:hover {
              background: #908b8b;
        }

        .bootstrap-datetimepicker-widget .glyphicon.glyphicon-time {
            color: white;
            font-weight: bold;
            font-size: 24px;
        }

        .bootstrap-datetimepicker-widget .glyphicon.glyphicon-calendar {
            color: white;
            font-weight: bold;
            font-size: 24px;
        }

        header {
            background-image: url({{ settings.HEADER_IMAGE }});
        }
    </style>
{% endblock %}

{% block body_class %}index{% endblock %}

{% block content_container %}
    <header>
        <div class="header-content index">
            <div class="row">
                <div class="col-sm-5">
                    <div class="panel" style="color: black !important;">
                        <div class="panel-body">
                            <form action="" method="post" class="form-horizontal" style="text-align: left;">{% csrf_token %}
                                {{ wizard.management_form }}
                                <div class="form-group">
                                    <div class="col-sm-12">
                                        {% for choice in wizard.form.booking_type %}
                                        <label class="radio-inline">
                                            {{ choice.tag }}
                                            {{ choice.choice_label }}
                                        </label>
                                        {% endfor %}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="{{ wizard.form.source.id_for_label }}" class="col-sm-2 control-label" style="text-align: left;">{{ wizard.form.source.label }}</label>
                                    <div class="col-sm-10">
                                        {{ wizard.form.source }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="{{ wizard.form.destination.id_for_label }}" class="col-sm-2 control-label" style="text-align: left;">{{ wizard.form.destination.label }}</label>
                                    <div class="col-sm-10">
                                        {{ wizard.form.destination }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-5">
                                        <div class="form-group" style="padding-right: 10px;">
                                            <label for="{{ wizard.form.travel_date.id_for_label }}" class="col-sm-12 control-label" style="padding-left: 0; text-align: left;">{{ wizard.form.travel_date.label }}</label>
                                            <div class="input-group date col-sm-12" id="traveldate-picker">
                                                {{ wizard.form.travel_date }}
                                                <span class="input-group-addon">
                                                    <span class="glyphicon glyphicon-calendar"></span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-sm-5">
                                        <div class="form-group" style="padding-left: 10px;">
                                            <label for="{{ wizard.form.travel_time.id_for_label }}" class="col-sm-12 control-label" style="text-align: left; padding-left: 0">{{ wizard.form.travel_time.label }}</label>
                                            <div class="input-group date col-sm-12" id="traveltime-picker">
                                                {{ wizard.form.travel_time }}
                                                <span class="input-group-addon">
                                                    <span class="glyphicon glyphicon-time"></span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-sm-2">
                                        <div class="form-group" style="padding-left: 10px;">
                                            <label for="{{ wizard.form.passengers.id_for_label }}" class="col-sm-12 control-label" style="text-align: left; padding-left: 0">{{ wizard.form.passengers.label }}</label>
                                            {{ wizard.form.passengers }}
                                        </div>
                                    </div>
                                </div>

                                <div style="text-align: center; padding-top: 10px;">
                                    <input type="submit" value="Search" class="btn btn-primary btn-xl"></input>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="header-content-inner col-sm-7">
                    <h1 id="homeHeading">{{ settings.PROJECT_HEADER }}</h1>
                    <hr>
                    <p>{{ settings.PROJECT_DESCRIPTION }}</p>
                </div>
			</div>
		</div>
	</header>

	{% comment %}
	<section id="features">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 text-center">
					<h2 class="section-heading">Features</h2>
					<hr class="primary">
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-6 text-center">
					<div class="service-box">
						<i class="fa fa-4x fa-magic text-primary sr-icons"></i>
						<h3>Sturdy Templates</h3>
						<p class="text-muted">Our templates are updated regularly so they don't break.</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 text-center">
					<div class="service-box">
						<i class="fa fa-4x fa-paper-plane text-primary sr-icons"></i>
						<h3>Ready to Ship</h3>
						<p class="text-muted">You can use this theme as is, or you can make changes!</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 text-center">
					<div class="service-box">
						<i class="fa fa-4x fa-newspaper-o text-primary sr-icons"></i>
						<h3>Up to Date</h3>
						<p class="text-muted">We update dependencies to keep things fresh.</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 text-center">
					<div class="service-box">
						<i class="fa fa-4x fa-heart text-primary sr-icons"></i>
						<h3>Made with Love</h3>
						<p class="text-muted">You have to make your websites with love these days!</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	{% endcomment %}

{% endblock %}

{% block scripts %}
{{ block.super }}
<script src="{% static "js/moment.min.js" %}"></script>
<script src="{% static "js/bootstrap-datetimepicker.min.js" %}"></script>
<script type="text/javascript">
$(function(){
    $('#id_itinerary-booking_type_0').click();

    $('#traveldate-picker').datetimepicker({
        minDate: moment(),
        maxDate:moment().add(120, 'd'),
        format: 'YYYY-MM-DD'
    });

    $('#traveltime-picker').datetimepicker({
        format: 'HH:mm'
    });

    $('#id_itinerary-source').on("change", function() {
         $('#id_itinerary-destination option').show();
         var value = $(this).val();
         $('#id_itinerary-destination option[value="'+value+'"]').hide();
    });

    $('#id_itinerary-destination').on("change", function() {
         $('#id_itinerary-source option').show();
         var value = $(this).val();
         $('#id_itinerary-source option[value="'+value+'"]').hide();
    });
});
</script>
{% endblock %}